language: ruby
cache:
- bundler
#rvm:
#- 2.6.1

before_install:
  - gem update --system
  - gem install bundler --pre

before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile

deploy:
  provider: heroku
  api_key:
    secure: c38dd210-60c4-4a56-9613-543d0c196b72
    app: backndprojectapp
  run:
    - "bundle exec rails db:migrate"


#language: ruby
#cache:
#- bundler
#before_script:
#- bundle exec rake db:create
#- bundle exec rake db:migrate
#- bundle exec rake assets:precompile
#deploy:
#  provider: heroku
#  api_key:
#    secure: KEY
#  app: rails-test-app-article
#  on:
#    repo: felipeluizsoares/rails-test-app